name: Init

permissions:
  contents: write
  actions: write

on:
  push:
    branches:
      - main

jobs:
  init:
    if: github.repository != 'gendloop/template-gendloopAction'
    runs-on: ubuntu-latest
    steps:
      - name: get-repo-name
        id: get-repo-name
        run: |
          repo_name=${GITHUB_REPOSITORY#*/}
          echo "reponame=$repo_name" >> "$GITHUB_OUTPUT"

      - name: replace-README
        uses: gendloop/replace-str@v1.0.1
        with:
          token: ${{ github.token }}
          path-to-replace: README.md
          replace-to-path: README.md
          str-to-replace: "RepoName"
          replace-to-str: ${{ steps.get-repo-name.outputs.reponame }}

      - name: replace-Template
        uses: gendloop/replace-str@v1.0.1
        with:
          token: ${{ github.token }}
          path-to-replace: Template.yml
          replace-to-path: Template.yml
          str-to-replace: "template-name"
          replace-to-str: ${{ steps.get-repo-name.outputs.reponame }}

      - name: remove
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
          Remove-Item .github/workflows/Init.yml

      - name: remove-useless-files-for-others
        if: ${{ github.actor != 'gendloop' }}
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
          Remove-Item scripts/downloadFilesFromRepo.json
          Remove-Item .github/workflows/Sync_Download.yml

      - name: git-push
        uses: gendloop/git-push@v1.0.0
        with:
          token: ${{ github.token }}
          commit: "chore: Remove Init.yml"
